# Generated by Django 5.0.2 on 2024-02-29 02:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XML',
            fields=[
                ('fname', models.CharField(max_length=255)),
                ('fcontent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'xmls',
            },
        ),
    ]
