# Generated by Django 5.0.2 on 2024-02-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_sxm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xml',
            old_name='fcontent',
            new_name='file_content',
        ),
        migrations.RenameField(
            model_name='xml',
            old_name='fname',
            new_name='file_name',
        ),
    ]
