# Generated by Django 5.0.2 on 2024-02-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_sxm', '0002_rename_fcontent_xml_file_content_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xml',
            table=None,
        ),
    ]
